export const COMMITTEE_CHARTER = [
  { letter: "a", name: "Finance Committee" },
  { letter: "b", name: "Missions Committee" },
  { letter: "c", name: "Estates & Projects Management" },
  { letter: "d", name: "Disciplinary Committee" },
  { letter: "e", name: "Media and Communications" },
  { letter: "f", name: "Information Technology" },
  { letter: "g", name: "Worship & Music" },
  { letter: "h", name: "Christian Education" },
  { letter: "i", name: "Evangelism & Outreach" },
  { letter: "j", name: "Youth Ministry" },
  { letter: "k", name: "Women's Fellowship" },
  { letter: "l", name: "Men's Fellowship" },
  { letter: "m", name: "Deacons Board" },
  { letter: "n", name: "Trustees Board" },
  { letter: "o", name: "Legal Affairs" },
  { letter: "p", name: "Hospitality & Ushering" },
  { letter: "q", name: "Building & Maintenance" },
  { letter: "r", name: "Social Welfare" },
  { letter: "s", name: "Pastoral Care" },
] as const;
